name: flutter_password_scoring
description: Helper library to score password strength with `dart_zxcvbn` and provide suggestions for improvement.
version: 0.0.2+3
homepage: https://github.com/inway/dart_zxcvbn
repository: https://github.com/inway/dart_zxcvbn

environment:
  sdk: ">=3.0.0 <4.0.0"
  flutter: ">=3.0.0"

dependencies:
  flutter:
    sdk: flutter
  dart_zxcvbn: ^0.1.0+4
  dart_zxcvbn_language_common: ^0.1.0+4

flutter:
