version: 2
updates:
  # Maintain dependencies for Dart
  - package-ecosystem: 'pub'
    directory: '/'
    schedule:
      interval: 'daily'
    commit-message:
      prefix: 'pub'
      prefix-development: 'pub dev'
      include: 'scope'
    versioning-strategy: 'increase'

  # Maintain dependencies for GitHub Actions
  - package-ecosystem: 'github-actions'
    directory: '/'
    schedule:
      interval: 'daily'
    commit-message:
      prefix: 'actions'
      prefix-development: 'actions dev'
      include: 'scope'


