name: dart_zxcvbn_tools
description: Shared tools for dart_zxcvbn for internal use with generating language packages from upstream data.
version: 0.0.1+2
homepage: https://github.com/inway/dart_zxcvbn
repository: https://github.com/inway/dart_zxcvbn

environment:
  sdk: ">=3.0.0 <4.0.0"
