name: dart_zxcvbn
description: A port of @zxcvbn-ts/zxcvbn to Dart. It provides a reasonable password strength estimator.
version: 0.1.0+1
homepage: https://github.com/inway/dart_zxcvbn
repository: https://github.com/inway/dart_zxcvbn

environment:
  sdk: ">=3.0.0 <4.0.0"

dependencies:
  collection: ^1.17.0

dev_dependencies:
  dart_zxcvbn_language_common: ^0.1.0+1
  dart_zxcvbn_language_en: ^0.1.0+1
  test: ^1.21.0
