name: dart_zxcvbn
description: A port of @zxcvbn-ts/zxcvbn to Dart.
version: 0.0.5
homepage: https://github.com/inway/dart_zxcvbn
repository: https://github.com/inway/dart_zxcvbn

environment:
  sdk: ">=3.0.0 <4.0.0"

dependencies:
  collection: ^1.17.0

dev_dependencies:
  dart_zxcvbn_language_common: ^0.0.1+7
  dart_zxcvbn_language_en: ^0.0.1+7
  test: ^1.21.0
