name: dart_zxcvbn_language_en
description: The English language package for dart_zxcvbn, provides translated messages and dictionaries.
version: 0.1.0
homepage: https://github.com/inway/dart_zxcvbn
repository: https://github.com/inway/dart_zxcvbn

environment:
  sdk: ">=3.0.0 <4.0.0"

dependencies:
  dart_zxcvbn: ^0.1.0
  intl: ^0.18.1

dev_dependencies:
  dart_zxcvbn_tools: ^0.0.1
  test: ^1.21.0
