name: example
description: "An example showing password scoring."
publish_to: "none"
version: 0.1.0

environment:
  sdk: ">=3.2.0 <4.0.0"

dependencies:
  flutter:
    sdk: flutter
  flutter_password_scoring:
    path: ../
  dart_zxcvbn: ^0.1.0+3
  dart_zxcvbn_language_common: ^0.1.0+3
  dart_zxcvbn_language_en: ^0.1.0+3

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^2.0.0

flutter:
  uses-material-design: true
