name: dart_zxcvbn_language_common
description: The common language package for dart_zxcvbn
version: 0.0.1+8
homepage: https://github.com/inway/dart_zxcvbn
repository: https://github.com/inway/dart_zxcvbn

environment:
  sdk: ">=3.0.0 <4.0.0"

dependencies:
  dart_zxcvbn: ^0.0.5

dev_dependencies:
  dart_zxcvbn_tools: ^0.0.1
  test: ^1.21.0
