name: Dart

on:
  push:
    branches: ["main"]
  pull_request:
    branches: ["main"]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4

      - uses: dart-lang/setup-dart@v1

      - name: Clone Flutter repository with stable channel
        uses: subosito/flutter-action@v2
        with:
          channel: stable
          cache: true

      - name: Dart pub cache
        uses: actions/cache@v3
        id: pub-cache
        with:
          path: ~/.pub-cache
          key: ${{ runner.os }}-pub-${{ hashFiles('pubspec.lock') }}
          restore-keys: |
            ${{ runner.os }}-pub-

      - name: Install Melos
        run: dart pub global activate melos

      - name: Bootstrap melos
        run: melos bootstrap

      - name: Verify formatting
        run: melos run format

      - name: Analyze project source
        run: melos run analyze

      - name: Run tests
        run: melos run test --no-select
